### ISSUE TITLE
weex create 报错

### ISSUE THREAD

**Issue by wqjGitHub** [weexteam/weex-hackernews#86]
weex 2.0.0-beta.4 创建项目：weex create e 错误
TypeError: Cannot read property 'error' of null
    at Cli.<anonymous> (/Users/*/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.4@@weex-cli/core/src/cli/cli.ts:188:17)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/*/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.4@@weex-cli/core/lib/cli/cli.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by foyel** [comment]
@erha19 最新版本在mac上还是有这个问题
